set_property IOSTANDARD LVCMOS33 [get_ports btn[3]]
set_property PACKAGE_PIN E4 [get_ports btn[3]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[2]]
set_property PACKAGE_PIN D4 [get_ports btn[2]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[1]]
set_property PACKAGE_PIN F5 [get_ports btn[1]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[0]]
set_property PACKAGE_PIN F4 [get_ports btn[0]]

set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property PACKAGE_PIN D5 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property PACKAGE_PIN D6 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN A5 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property PACKAGE_PIN B5 [get_ports led[0]]