set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property PACKAGE_PIN G6 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property PACKAGE_PIN H6 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sck]
set_property PACKAGE_PIN G7 [get_ports sck]
set_property IOSTANDARD LVCMOS33 [get_ports cs0]
set_property PACKAGE_PIN H7 [get_ports cs0]

set_property IOSTANDARD LVCMOS33 [get_ports cs1]
set_property PACKAGE_PIN J6 [get_ports cs1]
set_property IOSTANDARD LVCMOS33 [get_ports cs2]
set_property PACKAGE_PIN J7 [get_ports cs2]

set_property IOSTANDARD LVCMOS33 [get_ports pmodOut]
set_property PACKAGE_PIN H8 [get_ports pmodOut]

set_property IOSTANDARD LVCMOS33 [get_ports btn[3]]
set_property PACKAGE_PIN B4 [get_ports btn[3]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[2]]
set_property PACKAGE_PIN C4 [get_ports btn[2]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[1]]
set_property PACKAGE_PIN B3 [get_ports btn[1]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[0]]
set_property PACKAGE_PIN C3 [get_ports btn[0]]

set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property PACKAGE_PIN D5 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property PACKAGE_PIN D6 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN A5 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property PACKAGE_PIN B5 [get_ports led[0]]

set_property IOSTANDARD LVCMOS33 [get_ports squareWave]
set_property PACKAGE_PIN G8 [get_ports squareWave]